name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Ruby and CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Install CocoaPods
        run: |
          gem install cocoapods -N
          pod --version

      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pod install
        run: |
          cd ios
          pod repo update
          pod install --repo-update

      - name: Sanitize xcconfig flags
        run: |
          echo 'Before sanitize (matches with -G):'
          grep -R --line-number -E '\s-G(\s|$)' ios || true
          # Remove any -G tokens from all xcconfig files
          find ios -name '*.xcconfig' -print0 | xargs -0 sed -i '' -E 's/(^|[[:space:]])-G([[:space:]]|$)/ /g'
          echo 'After sanitize (should be empty):'
          grep -R --line-number -E '\s-G(\s|$)' ios || true

      - name: Copy Firebase config
        run: |
          if [ -f "GoogleService-Info.plist" ]; then
            cp GoogleService-Info.plist ios/Runner/
          else
            echo "GoogleService-Info.plist not found; skipping copy"
          fi

      - name: Build iOS (no codesign)
        env:
          CFLAGS: ''
          CXXFLAGS: ''
          OTHER_CFLAGS: ''
          OTHER_CPLUSPLUSFLAGS: ''
        run: flutter build ios --release --no-codesign

      - name: Prepare IPA
        run: |
          cd build/ios/iphoneos
          rm -rf Payload
          mkdir Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: englishapp-${{ github.run_number }}.ipa
          tag: build-${{ github.run_number }}
          overwrite: true
          body: "Build ${{ github.run_number }} release"
