name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 拉原始碼 + 支援 submodule
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 安裝 Flutter（建議與本地一致）
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: stable

      # 快取 pub 套件與 CocoaPods
      - name: Cache Flutter & CocoaPods
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ios/Pods
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # flutter doctor 檢查
      - name: Flutter Doctor
        run: flutter doctor

      # flutter clean
      - name: Clean project
        run: flutter clean

      # 取得 Flutter 相依套件
      - name: Install dependencies
        run: flutter pub get

      # 更新 CocoaPods
      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      # 建構 iOS App（不簽章）
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 建立 Payload 資料夾並移動 App
      - name: Prepare IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      # 上傳 IPA 到 GitHub Release
      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: englishapp-${{ github.run_number }}.ipa
          tag: build-${{ github.run_number }}
          overwrite: true
          body: "Build ${{ github.run_number }} release"
