name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 拉專案原始碼（支援 submodules）
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 安裝 Flutter（3.19.5 對應 Dart 3.3.3）
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: stable

      # 確認 Flutter 可用
      - name: Flutter doctor
        run: flutter doctor

      # 清掉舊的快取
      - name: Clean project
        run: flutter clean

      # 安裝套件
      - name: Install dependencies
        run: flutter pub get

      # 建構 iOS 專案（不簽名）
      - name: Build iOS (no code sign)
        run: flutter build ios --release --no-codesign

      # 使用 xcodebuild 轉成 .ipa（無簽章）
      - name: Create unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

      # 發佈到 GitHub Releases
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          name: iOS Release - ${{ github.run_number }}
          tag_name: ios-release-${{ github.run_number }}
          files: app.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
