name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 拉專案原始碼（支援 submodules）
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' # 改成 'recursive' 來正確拉取 submodule

      # 安裝指定版本 Flutter（對應 Dart 3.3）
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'

      # 檢查 Flutter 安裝成功
      - name: Flutter doctor
        run: flutter doctor

      # 清理專案，避免快取問題
      - name: Clean Flutter project
        run: flutter clean

      # 強制升級 Android 專案結構
      - name: Upgrade Android project
        run: flutter create --platforms=android .

      # 取得相依套件
      - name: Install dependencies
        run: flutter pub get

      # 建構 iOS（不簽章）
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 將 Runner.app 壓縮成 zip 檔
      - name: Zip iOS Build
        run: ditto -c -k --sequesterRsrc --keepParent build/ios/iphoneos/Runner.app Runner.zip

      # 建立 Release 並上傳 IPA
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          files: Runner.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
